turtlebot3: #namespace
    
    task_and_robot_environment_name: 'TurtleBot3World-v0' #Edit to change agent world env
    ros_ws_abspath: "/home/adrian/turtlebot_ws" #Edit to desired path 
    running_step: 0.04 # amount of time the control will be executed
    pos_step: 0.016     # increment in position for each command
    
    #ppo2 parameters
    
    gamma: 0.999
    nepisodes: 4  #Number of episodes to run. 
    nsteps: 10000
    running_step: 0.06 # Time for each step
    log_interval: 1000 #Number of timesteps before logging.
    save_freq: 1000 #Frequency of model checkpoints that will be saved durring training.
    total_timesteps: 100000